from collections import deque
queue = deque(["Eric","John","Michael"])
print(queue)
queue.append("Terry")
print(queue)
queue.append("Graham")
print(queue)
x = queue.popleft()
print(x,queue)
y = queue.popleft()
print(y,queue)